### ISSUE TITLE
close range gesture detection?

### ISSUE THREAD

**Issue by raomin** [melopero/Melopero_APDS-9960_Arduino_Library#2]
Hello @melopero.
Thanks for this advanced library for APDS 9660.
I am a bit struggling with the gesture detection and I thought maybe you could help.

I would like to detect the motion of a ball (left-to-right or right-to-left) as such:
![image](https://user-images.githubusercontent.com/4460208/164723506-b12a790c-3760-4376-9bce-0c106edd0bba.png)

But the fact that the max distance is small (6cm) seems to be an issue. I don't get any gesture.
Is it even possible with APDS?

**Comment by melopero** [comment]
Hello, 

Reading on the manufacturer website, "The proximity and gesture feature is factory-trimmed and calibrated to 100mm proximity detection distance without requiring customer calibrations":
https://www.broadcom.com/products/optical-sensors/integrated-ambient-light-and-proximity-sensors/apds-9960
